FROM alpine

ENV CONFIG=https://raw.githubusercontent.com/evillived/v2fly-cf/kintohub/config.json

RUN apk update && apk --no-cache add ca-certificates unzip && \
    wget -c https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip && \
    unzip v2ray-linux-64.zip && rm -f v2ray-linux-64.zip && \
    rm -f config.json && \
    rm -rf systemd* && \
    rm -f v2ctl.sig && \
    rm -f v2ray.sig && \
    rm -rf vpoint* && \
    mv v2ray myapp && \
    chmod 700 myapp v2ctl
    
CMD ./myapp -config $CONFIG
