FROM alpine

ENV CONFIG=https://raw.githubusercontent.com/evillived/myfirst/kintohub/config.json

RUN apk update && apk --no-cache add ca-certificates unzip && \
    wget -c https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip && \
    unzip v2ray-linux-64.zip && rm -f v2ray-linux-64.zip && \
    rm -f config.json && \
    rm -rf systemd* && \
    rm -f v2ctl.sig && \
    rm -f v2ray.sig && \
    rm -rf vpoint* && \
    mv v2ray ange && \
    mv v2ctl can && \
    chmod 700 ange can
    
CMD ./ange -config $CONFIG
